name: set build flag on push

on:
  push:
    paths: 
      - '*.sh'
      - '*.service'
      - '*.patch'
      - '*.conf'
      - '*.txt'
      - 'micon_scripts/*'
      
jobs:
 build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v1
   
   - name: set rebuild flag for autobuild process
     run: echo yes > .rebuild
     
    - name: setup git
      run: git config user.name "workflow@github"; git config user.email "workflow@github"
      
    - name: commit
      run: git commit -a -m "set rebuild flag"
      
    - name: push
      run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
