name: Update Components

on: [push]
  #schedule: 
    #- cron: 32 20 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      commit_needed: no
      repo_dir: .
    steps: 
    - name: check for micro-etvd update
      run: curl https://github.com/1000001101000/micro-evtd/raw/master/bins/micro-evtd-amd64 2>/dev/null | md5sum > /tmp/source 
    - name: check for micro-etvd update
      run: wget -O /tmp/micro-evtd-amd64 https://github.com/${{github.repository}}/raw/master/micro-evtd 2>/dev/null; cat /tmp/micro-evtd-amd64 | md5sum > /tmp/dest
    - name: check for micro-etvd update
      run: diff /tmp/source /tmp/dest || echo "needs update"; echo "::set-env name=commit_needed::yes"
      
    - name: if needed, clone the repo for update
      if: env.commit_needed == 'yes'
      run: git clone https://github.com/${{github.repository}}; echo "::set-env name=repo_dir::$(ls -rt | tail -n 1)"
    
    - name: if needed, copy file to repo
      if: env.commit_needed == 'yes'
      run: cp /tmp/micro-evtd-amd64 ./micro-evtd-amd64
    
    - name: if needed, setup git
      if: env.commit_needed == 'yes'
      run: git config user.name "workflow@github"; git config user.email "workflow@github"
      working-directory: "{{repo_dir}}"
      
    - name: if needed, commit
      if: env.commit_needed == 'yes'
      run: git commit -a -m "update files from external projects"
      working-directory: "{{repo_dir}}"
      
    #- name: if needed, push
    #  if: steps.build_images.outputs.commit_needed == 'yes'
    #  run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
    
      
    
